module.exports = {
  id: 'che',
  name: 'Chemical Engineering (International Program)',
  universityId: 'kmutt',
  courses: [
    // Year 1
    { code: 'GEN111', name: 'Man and Ethics of Living', yearLevel: 1 },
    { code: 'LNG221', name: 'Academic English for International Students', yearLevel: 1 },
    { code: 'MTH101', name: 'Mathematics I', yearLevel: 1 },
    { code: 'PHY103', name: 'General Physics for Engineering Students I', yearLevel: 1 },
    { code: 'PHY191', name: 'General Physics Laboratory I', yearLevel: 1 },
    { code: 'CHM103', name: 'Fundamental Chemistry', yearLevel: 1 },
    { code: 'CHM160', name: 'Chemistry Laboratory', yearLevel: 1 },
    { code: 'CHE101', name: 'Introduction to Chemical Engineering', yearLevel: 1 },
    { code: 'GEN101', name: 'Physical Education', yearLevel: 1 },
    { code: 'LNG222', name: 'Academic Listening and Speaking', yearLevel: 1 },
    { code: 'MTH102', name: 'Mathematics II', yearLevel: 1 },
    { code: 'PHY104', name: 'General Physics for Engineering Students II', yearLevel: 1 },
    { code: 'PHY192', name: 'General Physics Laboratory II', yearLevel: 1 },
    { code: 'MEE111', name: 'Engineering Drawing', yearLevel: 1 },
    { code: 'PRE151', name: 'Engineering Materials', yearLevel: 1 },
    { code: 'CHE102', name: 'Material and Energy Balances', yearLevel: 1 },

    // Year 2
    { code: 'GEN121', name: 'Learning and Problem Solving Skills', yearLevel: 2 },
    { code: 'LNG322', name: 'Academic Reading and Writing', yearLevel: 2 },
    { code: 'MTH201', name: 'Mathematics III', yearLevel: 2 },
    { code: 'MEE214', name: 'Engineering Mechanics', yearLevel: 2 },
    { code: 'CHE211', name: 'Industrial Organic Chemistry', yearLevel: 2 },
    { code: 'CHE212', name: 'Industrial Organic Chemistry Laboratory', yearLevel: 2 },
    { code: 'CHE221', name: 'Fundamentals of Momentum, Heat and Mass Transfer', yearLevel: 2 },
    { code: 'GEN231', name: 'Miracle of Thinking', yearLevel: 2 },
    { code: 'CHE213', name: 'Analytical Chemistry and Instrumentation', yearLevel: 2 },
    { code: 'CHE222', name: 'Fluid Mechanics and Equipment Design', yearLevel: 2 },
    { code: 'CHE231', name: 'Thermodynamics I', yearLevel: 2 },
    { code: 'EEE102', name: 'Electrotechnology I (Power)', yearLevel: 2 },

    // Year 3
    { code: 'GEN241', name: 'Beauty of Life', yearLevel: 3 },
    { code: 'CHE311', name: 'Thermodynamics II', yearLevel: 3 },
    { code: 'CHE321', name: 'Heat Transfer and Equipment Design', yearLevel: 3 },
    { code: 'CHE322', name: 'Chemical Kinetics and Reactor Design', yearLevel: 3 },
    { code: 'CHE331', name: 'Numerical Methods for Chemical Engineers', yearLevel: 3 },
    { code: 'CHE341', name: 'Chemical Engineering Laboratory I', yearLevel: 3 },
    { code: 'PRE380', name: 'Engineering Economics', yearLevel: 3 },
    { code: 'GEN351', name: 'Modern Management and Leadership', yearLevel: 3 },
    { code: 'CHE312', name: 'Mass Transfer and Equipment Design', yearLevel: 3 },
    { code: 'CHE332', name: 'Chemical Process Industries', yearLevel: 3 },
    { code: 'CHE342', name: 'Chemical Engineering Laboratory II', yearLevel: 3 },
    { code: 'CHE351', name: 'Process Dynamics and Control', yearLevel: 3 },
    { code: 'STA302', name: 'Probability and Statistics for Engineers', yearLevel: 3 },

    // Year 4
    { code: 'CHE421', name: 'Chemical Engineering Design Project I', yearLevel: 4 },
    { code: 'CHE431', name: 'Process Safety and Risk Management', yearLevel: 4 },
    { code: 'CHE441', name: 'Chemical Engineering Seminar', yearLevel: 4 },
    { code: 'CHE422', name: 'Chemical Engineering Design Project II', yearLevel: 4 },
    { code: 'CHE481', name: 'Professional Internship', yearLevel: 4 },
  ],
};
