module.exports = {
  id: 'cpe',
  name: 'Computer Engineering (International Program)',
  universityId: 'kmutt',
  courses: [
    // Year 1
    { code: 'CPE100', name: 'Computer Programming for Engineers', yearLevel: 1 },
    { code: 'CPE101', name: 'Engineering Exploration', yearLevel: 1 },
    { code: 'CPE111', name: 'Discrete Mathematics for Computer Engineers', yearLevel: 1 },
    { code: 'CPE123', name: 'User Experience/User Interface', yearLevel: 1 },
    { code: 'LNG221', name: 'Academic English for International Students', yearLevel: 1 },
    { code: 'MTH101', name: 'Mathematics I', yearLevel: 1 },
    { code: 'CPE112', name: 'Programming with Data Structures', yearLevel: 1 },
    { code: 'CPE121', name: 'Basic Circuits and Electronics', yearLevel: 1 },
    { code: 'GEN121', name: 'Learning and Problem Solving Skills', yearLevel: 1 },
    { code: 'LNG222', name: 'Academic Listening and Speaking for International Students', yearLevel: 1 },
    { code: 'MTH102', name: 'Mathematics II', yearLevel: 1 },
    { code: 'PHY103', name: 'General Physics for Engineering Student I', yearLevel: 1 },

    // Year 2
    { code: 'CPE222', name: 'Digital Electronics and Logic Design', yearLevel: 2 },
    { code: 'CPE231', name: 'Algorithms', yearLevel: 2 },
    { code: 'GEN101', name: 'Physical Education', yearLevel: 2 },
    { code: 'GEN231', name: 'Miracle of Thinking', yearLevel: 2 },
    { code: 'LNG321', name: 'Academic Reading and Writing for International Students', yearLevel: 2 },
    { code: 'MTH234', name: 'Linear Algebra', yearLevel: 2 },
    { code: 'PHY104', name: 'General Physics for Engineering Student II', yearLevel: 2 },
    { code: 'CPE223', name: 'Computer Architectures', yearLevel: 2 },
    { code: 'CPE232', name: 'Data Models', yearLevel: 2 },
    { code: 'CPE241', name: 'Database Systems', yearLevel: 2 },
    { code: 'GEN111', name: 'Man and Ethics of Living', yearLevel: 2 },
    { code: 'STA302', name: 'Statistics for Engineers', yearLevel: 2 },
    { code: 'CHM103', name: 'Fundamental Chemistry', yearLevel: 2 },

    // Year 3
    { code: 'CPE301', name: 'Professional Issues in Computer Engineering', yearLevel: 3 },
    { code: 'CPE333', name: 'Operating Systems', yearLevel: 3 },
    { code: 'CPE334', name: 'Software Engineering', yearLevel: 3 },
    { code: 'CPE371', name: 'Big Data Engineering', yearLevel: 3 },
    { code: 'GEN241', name: 'Beauty of Life', yearLevel: 3 },
    { code: 'PRE380', name: 'Engineering Economics', yearLevel: 3 },
    { code: 'CPE300', name: 'Computer Professional Practices', yearLevel: 3 },
    { code: 'CPE314', name: 'Computer Networks', yearLevel: 3 },
    { code: 'CPE343', name: 'Business Intelligence', yearLevel: 3 },
    { code: 'CPE351', name: 'Modern Management and Leadership', yearLevel: 3 },
    { code: 'CPE322', name: 'Digital Signal Processing', yearLevel: 3 },
    { code: 'CPE341', name: 'Computer Vision', yearLevel: 3 },
    { code: 'CPE331', name: 'Embedded Systems', yearLevel: 3 },

    // Year 4
    { code: 'CPE401', name: 'Computer Engineering Project I', yearLevel: 4 },
    { code: 'CPE402', name: 'Computer Engineering Project II', yearLevel: 4 },
    { code: 'CPE403', name: 'Independent Study I', yearLevel: 4 },
    { code: 'CPE404', name: 'Independent Study II', yearLevel: 4 },
    { code: 'CPE405', name: 'Work-Integrated Learning I', yearLevel: 4 },
    { code: 'CPE406', name: 'Work-Integrated Learning II', yearLevel: 4 },
    { code: 'CPE415', name: 'Artificial Intelligence', yearLevel: 4 },
    { code: 'CPE421', name: 'Machine Learning', yearLevel: 4 },
    { code: 'CPE425', name: 'Data Mining', yearLevel: 4 },
    { code: 'CPE466', name: 'Natural Language Processing', yearLevel: 4 },
    { code: 'CPE432', name: 'Mobile Application Development', yearLevel: 4 },
    { code: 'CPE435', name: 'Cloud Computing', yearLevel: 4 },
    { code: 'CPE440', name: 'IoT Systems', yearLevel: 4 },
    { code: 'CPE455', name: 'Advanced Network Security', yearLevel: 4 },
    { code: 'CPE480', name: 'Robotics', yearLevel: 4 },
    { code: 'CPE490', name: 'Special Topics in Computer Engineering I', yearLevel: 4 },
    { code: 'CPE491', name: 'Special Topics in Computer Engineering II', yearLevel: 4 },
  ],
};
