module.exports = {
  id: 'cve',
  name: 'Civil Engineering (International Program)',
  universityId: 'kmutt',
  courses: [
    // Year 1
    { code: 'GEN101', name: 'Physical Education', yearLevel: 1 },
    { code: 'GEN111', name: 'Man and Ethics of Living', yearLevel: 1 },
    { code: 'GEN121', name: 'Learning and Problem Solving Skills', yearLevel: 1 },
    { code: 'LNG221', name: 'Academic English in International Contexts', yearLevel: 1 },
    { code: 'LNG222', name: 'Academic Listening and Speaking in International Contexts', yearLevel: 1 },
    { code: 'MTH101', name: 'Mathematics I', yearLevel: 1 },
    { code: 'PHY103', name: 'General Physics for Engineering Students I', yearLevel: 1 },
    { code: 'PHY191', name: 'General Physics Laboratory I', yearLevel: 1 },
    { code: 'CHM103', name: 'Fundamental Chemistry', yearLevel: 1 },
    { code: 'CHM160', name: 'Chemistry Laboratory', yearLevel: 1 },
    { code: 'MEN111', name: 'Engineering Materials', yearLevel: 1 },
    { code: 'CVE100', name: 'Computer Programming for Civil Engineering', yearLevel: 1 },
    { code: 'CVE101', name: 'World of Civil Engineering', yearLevel: 1 },
    { code: 'CVE111', name: 'Engineering Drawing', yearLevel: 1 },
    { code: 'CVE231', name: 'Engineering Mechanics', yearLevel: 1 },
    { code: 'MTH102', name: 'Mathematics II', yearLevel: 1 },
    { code: 'PHY104', name: 'General Physics for Engineering Students II', yearLevel: 1 },
    { code: 'PHY192', name: 'General Physics Laboratory II', yearLevel: 1 },

    // Year 2
    { code: 'GEN231', name: 'Miracle of Thinking', yearLevel: 2 },
    { code: 'GEN241', name: 'Beauty of Life', yearLevel: 2 },
    { code: 'LNG321', name: 'Academic Reading and Writing in International Contexts', yearLevel: 2 },
    { code: 'MTH201', name: 'Mathematics III', yearLevel: 2 },
    { code: 'CVE200', name: 'Statistics for Civil Engineering', yearLevel: 2 },
    { code: 'CVE216', name: 'Principles of Finance, Investment and Decision-making', yearLevel: 2 },
    { code: 'CVE221', name: 'Surveying', yearLevel: 2 },
    { code: 'CVE223', name: 'Surveying Practices', yearLevel: 2 },
    { code: 'CVE225', name: 'Surveying Field Camp', yearLevel: 2 },
    { code: 'CVE233', name: 'Mechanics of Materials', yearLevel: 2 },
    { code: 'CVE236', name: 'Civil Engineering Materials', yearLevel: 2 },
    { code: 'CVE240', name: 'Applied Mathematics for Civil Engineers', yearLevel: 2 },
    { code: 'CVE281', name: 'Fluid Mechanics', yearLevel: 2 },

    // Year 3
    { code: 'CVE300', name: 'Industrial Training', yearLevel: 3 },
    { code: 'CVE303', name: 'Milestone Design Project', yearLevel: 3 },
    { code: 'CVE335', name: 'Application of Civil Engineering Materials', yearLevel: 3 },
    { code: 'CVE337', name: 'Structural Analysis I', yearLevel: 3 },
    { code: 'CVE338', name: 'Structural Analysis II', yearLevel: 3 },
    { code: 'CVE345', name: 'Steel and Timber Design', yearLevel: 3 },
    { code: 'CVE346', name: 'Reinforced Concrete Design', yearLevel: 3 },
    { code: 'CVE362', name: 'Soil Mechanics', yearLevel: 3 },
    { code: 'CVE363', name: 'Soil Mechanics Laboratory', yearLevel: 3 },
    { code: 'CVE364', name: 'Foundation Engineering', yearLevel: 3 },
    { code: 'CVE371', name: 'Highway Engineering', yearLevel: 3 },
    { code: 'CVE382', name: 'Hydraulic Engineering', yearLevel: 3 },
    { code: 'CVE386', name: 'Hydrosphere', yearLevel: 3 },
    { code: 'CVE394', name: 'Hydraulics Laboratory', yearLevel: 3 },

    // Year 4
    { code: 'GEN351', name: 'Modern Management and Leadership', yearLevel: 4 },
    { code: 'CVE408', name: 'Civil Engineering Capstone Project Proposal', yearLevel: 4 },
    { code: 'CVE409', name: 'Civil Engineering Capstone Project', yearLevel: 4 },
    { code: 'CVE415', name: 'Construction Management', yearLevel: 4 },
    { code: 'CVE472', name: 'Transportation Engineering', yearLevel: 4 },
    { code: 'CVE404', name: 'Special Topic I', yearLevel: 4 },
    { code: 'CVE405', name: 'Special Topic II', yearLevel: 4 },
    { code: 'CVE406', name: 'Cooperative Education', yearLevel: 4 },
    { code: 'CVE407', name: 'Cooperative Seminar', yearLevel: 4 },
    { code: 'CVE411', name: 'Modern Construction Engineering and Technology', yearLevel: 4 },
    { code: 'CVE414', name: 'Construction Estimating and Specifications', yearLevel: 4 },
    { code: 'CVE418', name: 'Information Technology in Construction', yearLevel: 4 },
    { code: 'CVE426', name: 'Digital Photogrammetry', yearLevel: 4 },
    { code: 'CVE427', name: 'Satellite Image Analysis', yearLevel: 4 },
    { code: 'CVE428', name: 'Satellite Surveying', yearLevel: 4 },
    { code: 'CVE429', name: 'Introduction to Geographic Information System', yearLevel: 4 },
    { code: 'CVE444', name: 'Prestressed Concrete Design', yearLevel: 4 },
    { code: 'CVE447', name: 'Civil Engineering Design', yearLevel: 4 },
    { code: 'CVE448', name: 'Fundamental of Finite Element Method', yearLevel: 4 },
    { code: 'CVE465', name: 'Geotechnical Engineering Design', yearLevel: 4 },
    { code: 'CVE466', name: 'Geotechnical Earthquake Engineering', yearLevel: 4 },
    { code: 'CVE473', name: 'Traffic Engineering', yearLevel: 4 },
    { code: 'CVE474', name: 'Urban Transportation Systems', yearLevel: 4 },
    { code: 'CVE475', name: 'Logistics Management', yearLevel: 4 },
    { code: 'CVE483', name: 'Water Resource Development', yearLevel: 4 },
    { code: 'CVE484', name: 'Water Resources Engineering Project Planning', yearLevel: 4 },
    { code: 'CVE487', name: 'Hydraulic Structures', yearLevel: 4 },
    { code: 'CVE490', name: 'Applied Hydrology', yearLevel: 4 },
  ],
};
