module.exports = {
  id: 'dt',
  name: 'Creative Technology (International Program)',
  universityId: 'kmutt',
  courses: [
    // Year 1
    { code: 'DD100', name: 'Introduction to Psychology for Digital Media', yearLevel: 1 },
    { code: 'DT100', name: 'Fundamentals of Mathematics for Computer Graphics', yearLevel: 1 },
    { code: 'DT101', name: 'Fundamentals of Mathematics for Computer Graphics Lab', yearLevel: 1 },
    { code: 'DT110', name: 'Applied Calculus and Analytic Geometry 1', yearLevel: 1 },
    { code: 'DT130', name: 'Project Introduction', yearLevel: 1 },
    { code: 'DT131', name: 'Project', yearLevel: 1 },
    { code: 'DT160', name: 'High Level Programming', yearLevel: 1 },
    { code: 'DT161', name: 'High Level Programming Lab', yearLevel: 1 },
    { code: 'DT162', name: 'Object-Oriented Programming', yearLevel: 1 },
    { code: 'DT163', name: 'Object-Oriented Programming Lab', yearLevel: 1 },
    { code: 'DT170', name: 'Game Design and Implementation Techniques', yearLevel: 1 },
    { code: 'DT180', name: 'Computer Organization and Architecture', yearLevel: 1 },
    { code: 'DT181', name: 'Computer Organization and Architecture Lab', yearLevel: 1 },

    // Year 2
    { code: 'DT200', name: 'Applied Calculus and Analytic Geometry 2', yearLevel: 2 },
    { code: 'DT201', name: 'Linear Algebra', yearLevel: 2 },
    { code: 'DT210', name: 'Dynamics', yearLevel: 2 },
    { code: 'DT211', name: 'Dynamics Lab', yearLevel: 2 },
    { code: 'DT230', name: 'Advance Project 1', yearLevel: 2 },
    { code: 'DT231', name: 'Advance Project 2', yearLevel: 2 },
    { code: 'DT247', name: 'Theory and Principles of Game Design 1', yearLevel: 2 },
    { code: 'DT257', name: 'Theory and Principles of Game Design 2', yearLevel: 2 },
    { code: 'DT260', name: 'Advance Programming', yearLevel: 2 },
    { code: 'DT261', name: 'Data Structures', yearLevel: 2 },
    { code: 'DT280', name: 'Operating Systems', yearLevel: 2 },
    { code: 'DT284', name: 'Computer Graphics 1', yearLevel: 2 },
    { code: 'DT285', name: 'Computer Graphics 2', yearLevel: 2 },

    // Year 3
    { code: 'DT300', name: 'Discrete Structures', yearLevel: 3 },
    { code: 'DT328', name: 'Graphic and User Experience Design', yearLevel: 3 },
    { code: 'DT330', name: 'Special Topic for Interactive Simulation 1', yearLevel: 3 },
    { code: 'DT331', name: 'Special Topic for Interactive Simulation 2', yearLevel: 3 },
    { code: 'DT332', name: 'Field Training', yearLevel: 3 },
    { code: 'DT333', name: 'Experiential Learning Preparation', yearLevel: 3 },
    { code: 'DT334', name: 'Special Topic for Game Engineering 1', yearLevel: 3 },
    { code: 'DT335', name: 'Special Topic for Game Engineering 2', yearLevel: 3 },
    { code: 'DT347', name: 'Game Space and Camera Design', yearLevel: 3 },
  ],
};
