module.exports = {
  id: 'env',
  name: 'Environmental Engineering (International Program)',
  universityId: 'kmutt',
  courses: [
    // Year 1
    { code: 'CPE100', name: 'Computer Programming for Engineers', yearLevel: 1 },
    { code: 'CVE111', name: 'Engineering Drawing', yearLevel: 1 },
    { code: 'LNG221', name: 'Academic English for International Students', yearLevel: 1 },
    { code: 'PRE151', name: 'Engineering Materials', yearLevel: 1 },
    { code: 'MTH101', name: 'Mathematics I', yearLevel: 1 },
    { code: 'PHY103', name: 'General Physics for Engineering Student I', yearLevel: 1 },
    { code: 'PHY191', name: 'General Physics Laboratory I', yearLevel: 1 },
    { code: 'CHM103', name: 'Fundamental Chemistry', yearLevel: 1 },
    { code: 'GEN111', name: 'Man and Ethics of Living', yearLevel: 1 },
    { code: 'LNG222', name: 'Academic Listening and Speaking', yearLevel: 1 },
    { code: 'CVE131', name: 'Engineering Mechanics I', yearLevel: 1 },
    { code: 'MTH102', name: 'Mathematics II', yearLevel: 1 },
    { code: 'PHY104', name: 'General Physics for Engineering Student II', yearLevel: 1 },
    { code: 'PHY192', name: 'General Physics Laboratory II', yearLevel: 1 },

    // Year 2
    { code: 'GEN121', name: 'Learning and Problem Solving Skills', yearLevel: 2 },
    { code: 'LNG322', name: 'Academic Reading and Writing', yearLevel: 2 },
    { code: 'EEE100', name: 'Electrotechnology I (Power)', yearLevel: 2 },
    { code: 'MTH201', name: 'Mathematics III', yearLevel: 2 },
    { code: 'ENV210', name: 'Fundamentals in Environmental Engineering', yearLevel: 2 },
    { code: 'ENV213', name: 'Surveying for Environmental Engineering', yearLevel: 2 },
    { code: 'GEN231', name: 'Miracle of Thinking', yearLevel: 2 },
    { code: 'CVE282', name: 'Hydraulics for Environmental Engineering', yearLevel: 2 },
    { code: 'ENV211', name: 'Environmental Chemistry', yearLevel: 2 },
    { code: 'ENV212', name: 'Environmental Chemistry and Microbiology Laboratory', yearLevel: 2 },
    { code: 'ENV214', name: 'Environmental Engineering Statistics', yearLevel: 2 },
    { code: 'ENV215', name: 'Environmental Biology', yearLevel: 2 },

    // Year 3
    { code: 'GEN241', name: 'Beauty of Life', yearLevel: 3 },
    { code: 'CVE385', name: 'Hydrology', yearLevel: 3 },
    { code: 'ENV341', name: 'Unit Operation in Environmental Engineering', yearLevel: 3 },
    { code: 'ENV344', name: 'Biological Unit Processes in Environmental Engineering', yearLevel: 3 },
    { code: 'ENV345', name: 'Environmental Engineering Laboratory', yearLevel: 3 },
    { code: 'ENV371', name: 'Solid Waste Management', yearLevel: 3 },
    { code: 'GEN351', name: 'Modern Management and Leadership', yearLevel: 3 },
    { code: 'ENV342', name: 'Water Supply Engineering', yearLevel: 3 },
    { code: 'ENV343', name: 'Wastewater Engineering', yearLevel: 3 },
    { code: 'ENV372', name: 'Air Pollution Control', yearLevel: 3 },
    { code: 'ENV373', name: 'Hazardous Waste Management', yearLevel: 3 },
    { code: 'PRE380', name: 'Engineering Economics', yearLevel: 3 },

    // Year 4
    { code: 'ENV451', name: 'Environmental Engineering Design Project I', yearLevel: 4 },
    { code: 'ENV461', name: 'Environmental Engineering Seminar', yearLevel: 4 },
    { code: 'ENV452', name: 'Environmental Engineering Design Project II', yearLevel: 4 },
    { code: 'ENV481', name: 'Environmental Engineering Internship', yearLevel: 4 },
  ],
};
