module.exports = {
  id: 'inc',
  name: 'Automation Engineering (International Program)',
  universityId: 'kmutt',
  courses: [
    // Year 1
    { code: 'GEN111', name: 'Man and Ethics of Living', yearLevel: 1 },
    { code: 'LNG221', name: 'Academic English for International Students', yearLevel: 1 },
    { code: 'MTH101', name: 'Mathematics I', yearLevel: 1 },
    { code: 'PHY103', name: 'General Physics for Engineering Students I', yearLevel: 1 },
    { code: 'PHY191', name: 'General Physics Laboratory I', yearLevel: 1 },
    { code: 'MEE115', name: 'Engineering Drawing', yearLevel: 1 },
    { code: 'CPE101', name: 'Computer Engineering Exploration', yearLevel: 1 },
    { code: 'GEN101', name: 'Physical Education', yearLevel: 1 },
    { code: 'GEN121', name: 'Learning and Problem Solving Skills', yearLevel: 1 },
    { code: 'LNG222', name: 'Academic Listening and Speaking', yearLevel: 1 },
    { code: 'CHM103', name: 'Fundamental Chemistry', yearLevel: 1 },
    { code: 'MTH102', name: 'Mathematics II', yearLevel: 1 },
    { code: 'INC123', name: 'Electric Circuit Analysis for Automation Engineering', yearLevel: 1 },
    { code: 'INC142', name: 'Computer Programming for Automation Engineering', yearLevel: 1 },

    // Year 2
    { code: 'GEN241', name: 'Beauty of Life', yearLevel: 2 },
    { code: 'MTH201', name: 'Mathematics III', yearLevel: 2 },
    { code: 'LNG322', name: 'Academic Writing I', yearLevel: 2 },
    { code: 'INC222', name: 'Electronics for Automation Systems', yearLevel: 2 },
    { code: 'INC224', name: 'Digital Systems', yearLevel: 2 },
    { code: 'INC225', name: 'Electronic and Digital Laboratory for Automation Engineering Students', yearLevel: 2 },
    { code: 'INC242', name: 'Data Structures and Algorithms', yearLevel: 2 },
    { code: 'GEN231', name: 'Miracle of Thinking', yearLevel: 2 },
    { code: 'EEE102', name: 'Electrotechnology I (Power)', yearLevel: 2 },
    { code: 'INC233', name: 'Signals and Systems for Automation Engineering', yearLevel: 2 },
    { code: 'INC234', name: 'System Modelling and Analysis', yearLevel: 2 },
    { code: 'INC251', name: 'Programmable Logic Control', yearLevel: 2 },
    { code: 'INC261', name: 'Data Management', yearLevel: 2 },
    { code: 'INC272', name: 'Capstone Project I for Automation Engineering Students', yearLevel: 2 },

    // Year 3
    { code: 'CPE314', name: 'Computer Networks', yearLevel: 3 },
    { code: 'INC332', name: 'Feedback Control System', yearLevel: 3 },
    { code: 'INC351', name: 'Basic Engineering Statistics and Basic Manufacturing Process', yearLevel: 3 },
    { code: 'INC352', name: 'Industrial Process Measurement', yearLevel: 3 },
    { code: 'INC353', name: 'Process Control System and Instrumentation Drawing', yearLevel: 3 },
    { code: 'INC361', name: 'Digital Factory Technologies', yearLevel: 3 },
    { code: 'INC362', name: 'Introduction of Data Science for Automation', yearLevel: 3 },
    { code: 'MEE224', name: 'Thermal Engineering', yearLevel: 3 },
    { code: 'INC343', name: 'Computer-based Control and Monitoring Systems', yearLevel: 3 },
    { code: 'INC355', name: 'Process Automation Design', yearLevel: 3 },
    { code: 'INC363', name: 'Manufacturing Execution System', yearLevel: 3 },
    { code: 'INC364', name: 'Financial and Managerial Accounting for ERP System', yearLevel: 3 },
    { code: 'INC382', name: 'Capstone Project II for Automation Engineering Students', yearLevel: 3 },
    { code: 'INC381', name: 'Industrial Training', yearLevel: 3 },

    // Year 4
    { code: 'GEN351', name: 'Modern Management and Leadership', yearLevel: 4 },
    { code: 'INC411', name: 'Industrial Safety', yearLevel: 4 },
    { code: 'INC472', name: 'Automation Engineering Project Study', yearLevel: 4 },
    { code: 'INC476', name: 'Automation Engineering Project', yearLevel: 4 },
  ],
};
