module.exports = {
  id: 'it',
  name: 'Information Technology',
  universityId: 'kmutt',
  courses: [
    // Year 1
    { code: 'INT100', name: 'Design Thinking', yearLevel: 1 },
    { code: 'INT101', name: 'Discrete Mathematics', yearLevel: 1 },
    { code: 'INT110', name: 'Business Thinking', yearLevel: 1 },
    { code: 'INT120', name: 'UX/UI Design Fundamentals', yearLevel: 1 },
    { code: 'INT130', name: 'Computing Platform Basics', yearLevel: 1 },
    { code: 'INT140', name: 'Computational Thinking', yearLevel: 1 },
    { code: 'INT143', name: 'Software Process Fundamentals', yearLevel: 1 },
    { code: 'INT180', name: 'Data Literacy', yearLevel: 1 },
    { code: 'INT131', name: 'Computing Platform Principles', yearLevel: 1 },
    { code: 'INT132', name: 'Linux Fundamentals and Shell Scripting', yearLevel: 1 },
    { code: 'INT133', name: 'Computer Networks', yearLevel: 1 },
    { code: 'INT135', name: 'Basic Security', yearLevel: 1 },
    { code: 'INT141', name: 'Basic Programming', yearLevel: 1 },
    { code: 'INT142', name: 'Software Development Tools', yearLevel: 1 },
    { code: 'INT150', name: 'Web Technology', yearLevel: 1 },
    { code: 'INT190', name: 'Basic SQL', yearLevel: 1 },

    // Year 2
    { code: 'INT134', name: 'System Deployment', yearLevel: 2 },
    { code: 'INT144', name: 'Agile Software Development I', yearLevel: 2 },
    { code: 'INT151', name: 'Basic Frontend Development', yearLevel: 2 },
    { code: 'INT161', name: 'Basic Backend Development', yearLevel: 2 },
    { code: 'INT182', name: 'Data Science and Artificial Intelligence Fundamentals', yearLevel: 2 },
    { code: 'INT191', name: 'Relational Database Concepts and Design', yearLevel: 2 },
    { code: 'INT504', name: 'Integrated Project', yearLevel: 2 },
    { code: 'INT102', name: 'Statistics for Information Technology', yearLevel: 2 },
    { code: 'INT111', name: 'Business Information Systems', yearLevel: 2 },
    { code: 'INT185', name: 'Basic Data Visualization', yearLevel: 2 },

    // Year 3
    { code: 'INT105', name: 'Information Technology Seminar', yearLevel: 3 },
    { code: 'INT136', name: 'Cyber Security', yearLevel: 3 },
    { code: 'INT145', name: 'Software Analysis and Design', yearLevel: 3 },
    { code: 'INT240', name: 'Advanced Programming Concepts', yearLevel: 3 },
    { code: 'INT242', name: 'Java Programming', yearLevel: 3 },
    { code: 'INT243', name: 'Python Programming', yearLevel: 3 },
    { code: 'INT250', name: 'CSS Framework', yearLevel: 3 },
    { code: 'INT270', name: 'Mathematics for Artificial Intelligence', yearLevel: 3 },
    { code: 'INT282', name: 'Statistics for Data Science', yearLevel: 3 },
    { code: 'INT116', name: 'Legal and Ethical Issues in Information Technology', yearLevel: 3 },
    { code: 'INT146', name: 'Software Testing', yearLevel: 3 },
    { code: 'INT189', name: 'Data Governance', yearLevel: 3 },
    { code: 'INT241', name: 'Data Structures and Algorithms', yearLevel: 3 },
    { code: 'INT251', name: 'Frontend Development Framework', yearLevel: 3 },
    { code: 'INT261', name: 'Backend Development Framework', yearLevel: 3 },
    { code: 'INT271', name: 'Machine Learning', yearLevel: 3 },
    { code: 'INT272', name: 'Artificial Neural Networks and Deep Learning', yearLevel: 3 },
    { code: 'INT273', name: 'Generative Deep Learning', yearLevel: 3 },
    { code: 'INT285', name: 'Advanced Data Visualization', yearLevel: 3 },
    { code: 'INT297', name: 'NoSQL Database', yearLevel: 3 },

    // Year 4
    { code: 'INT115', name: 'Information Technology Professional Practices', yearLevel: 4 },
    { code: 'INT147', name: 'Agile Software Development II', yearLevel: 4 },
    { code: 'INT505', name: 'Capstone Project I', yearLevel: 4 },
    { code: 'INT506', name: 'Capstone Project II', yearLevel: 4 },
    { code: 'INT507', name: 'Research Project I', yearLevel: 4 },
    { code: 'INT508', name: 'Research Project II', yearLevel: 4 },
    { code: 'INT509', name: 'Experiential Learning', yearLevel: 4 },
  ],
};
