name = "unishare-upload"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
FIREBASE_PROJECT_ID = "unishare-flutter"
R2_PUBLIC_URL = "https://cdn.psstee.dev"
